version: '8.2.12'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=hastaneotomasyonu
      - MYSQL_USER=root@localhost
      - MYSQL_PASSWORD= # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  www:
    image: php:apache
    volumes:
      - "./http://localhost" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306